# Generated by Django 5.2.6 on 2025-10-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberintel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CweSoftwareDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_id', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('weakness_abstraction', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('extended_description', models.TextField(blank=True)),
                ('related_weaknesses', models.TextField(blank=True)),
                ('weakness_ordinalities', models.TextField(blank=True)),
                ('applicable_platforms', models.TextField(blank=True)),
                ('background_details', models.TextField(blank=True)),
                ('alternate_terms', models.TextField(blank=True)),
                ('modes_of_introduction', models.TextField(blank=True)),
                ('exploitation_factors', models.TextField(blank=True)),
                ('likelihood_of_exploit', models.TextField(blank=True)),
                ('common_consequences', models.TextField(blank=True)),
                ('detection_methods', models.TextField(blank=True)),
                ('potential_mitigations', models.TextField(blank=True)),
                ('observed_examples', models.TextField(blank=True)),
                ('functional_areas', models.TextField(blank=True)),
                ('affected_resources', models.TextField(blank=True)),
                ('taxonomy_mappings', models.TextField(blank=True)),
                ('related_attack_patterns', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cwe_software_development',
            },
        ),
    ]
