# Generated by Django 5.2.6 on 2025-10-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberintel', '0002_cwesoftwaredevelopment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NvdDataEnriched',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('published', models.TextField(blank=True)),
                ('vulnstatus', models.TextField(blank=True, db_column='vulnStatus')),
                ('lang', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('cwe_id', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('weakness_abstraction', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('extended_description', models.TextField(blank=True)),
                ('alternate_terms', models.TextField(blank=True)),
                ('modes_of_introduction', models.TextField(blank=True)),
                ('common_consequences', models.TextField(blank=True)),
                ('detection_methods', models.TextField(blank=True)),
                ('potential_mitigations', models.TextField(blank=True)),
                ('observed_examples', models.TextField(blank=True)),
                ('functional_areas', models.TextField(blank=True)),
                ('affected_resources', models.TextField(blank=True)),
                ('taxonomy_mappings', models.TextField(blank=True)),
                ('related_attack_patterns', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cwe_source', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'nvd_data_enriched',
            },
        ),
    ]
