# Generated by Django 4.2.7 on 2025-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberintel', '0003_nvddataenriched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('threat_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_level', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cwesoftwaredevelopment',
            name='id',
        ),
        migrations.AlterField(
            model_name='cwesoftwaredevelopment',
            name='cwe_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
