# Generated by Django 4.2.7 on 2025-11-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberintel', '0004_threat_remove_cwesoftwaredevelopment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('region_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('cve_id', models.CharField(max_length=50)),
                ('epss', models.FloatField()),
                ('cvss_version', models.FloatField()),
            ],
        ),
    ]
